
The following have been reloaded with a version change:
  1) anaconda2/4.4.0 => anaconda2/5.1.0

/apps/software/standard/mpi/gcc/7.1.0/openmpi/2.1.1/anaconda2/5.1.0/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2957 [1;31mRuntimeWarning[0m: Mean of empty slice.
/apps/software/standard/mpi/gcc/7.1.0/openmpi/2.1.1/anaconda2/5.1.0/lib/python2.7/site-packages/numpy/core/_methods.py:80 [1;31mRuntimeWarning[0m: invalid value encountered in double_scalars
